name: React Sample CI-CD
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Echo node version
        run: node -v
      - name: Echo github context
        run: echo "${{ toJson(github)}}"
